/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DisplayIndexRouteImport } from './routes/display/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as STokenRouteImport } from './routes/s/$token'
import { Route as GymsJoinRouteImport } from './routes/gyms.join'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedCommsRouteImport } from './routes/_authenticated/comms'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedExercisesIndexRouteImport } from './routes/_authenticated/exercises/index'
import { Route as DisplayGymGymIdRouteImport } from './routes/display/gym/$gymId'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates.new'
import { Route as AuthenticatedLogNewRouteImport } from './routes/_authenticated/log.new'
import { Route as AuthenticatedLogWorkoutIdRouteImport } from './routes/_authenticated/log.$workoutId'
import { Route as AuthenticatedHistoryWorkoutIdRouteImport } from './routes/_authenticated/history/$workoutId'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AuthenticatedExercisesExerciseIdRouteImport } from './routes/_authenticated/exercises/$exerciseId'
import { Route as AuthenticatedEventsTemplateIdRouteImport } from './routes/_authenticated/events.$templateId'
import { Route as AuthenticatedCommsConversationIdRouteImport } from './routes/_authenticated/comms.$conversationId'
import { Route as AuthenticatedTemplatesTemplateIdEditRouteImport } from './routes/_authenticated/templates.$templateId.edit'
import { Route as AuthenticatedProfileGymsGymIdRouteImport } from './routes/_authenticated/profile.gyms.$gymId'
import { Route as AuthenticatedLogWorkoutIdEditRouteImport } from './routes/_authenticated/log.$workoutId.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayIndexRoute = DisplayIndexRouteImport.update({
  id: '/display/',
  path: '/display/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GymsJoinRoute = GymsJoinRouteImport.update({
  id: '/gyms/join',
  path: '/gyms/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommsRoute = AuthenticatedCommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExercisesIndexRoute =
  AuthenticatedExercisesIndexRouteImport.update({
    id: '/exercises/',
    path: '/exercises/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DisplayGymGymIdRoute = DisplayGymGymIdRouteImport.update({
  id: '/display/gym/$gymId',
  path: '/display/gym/$gymId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogNewRoute = AuthenticatedLogNewRouteImport.update({
  id: '/log/new',
  path: '/log/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogWorkoutIdRoute =
  AuthenticatedLogWorkoutIdRouteImport.update({
    id: '/log/$workoutId',
    path: '/log/$workoutId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryWorkoutIdRoute =
  AuthenticatedHistoryWorkoutIdRouteImport.update({
    id: '/history/$workoutId',
    path: '/history/$workoutId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedExercisesExerciseIdRoute =
  AuthenticatedExercisesExerciseIdRouteImport.update({
    id: '/exercises/$exerciseId',
    path: '/exercises/$exerciseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsTemplateIdRoute =
  AuthenticatedEventsTemplateIdRouteImport.update({
    id: '/events/$templateId',
    path: '/events/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommsConversationIdRoute =
  AuthenticatedCommsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedCommsRoute,
  } as any)
const AuthenticatedTemplatesTemplateIdEditRoute =
  AuthenticatedTemplatesTemplateIdEditRouteImport.update({
    id: '/templates/$templateId/edit',
    path: '/templates/$templateId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileGymsGymIdRoute =
  AuthenticatedProfileGymsGymIdRouteImport.update({
    id: '/gyms/$gymId',
    path: '/gyms/$gymId',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedLogWorkoutIdEditRoute =
  AuthenticatedLogWorkoutIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedLogWorkoutIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/connect': typeof ConnectRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/comms': typeof AuthenticatedCommsRouteWithChildren
  '/connections': typeof AuthenticatedConnectionsRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gyms/join': typeof GymsJoinRoute
  '/s/$token': typeof STokenRoute
  '/display/': typeof DisplayIndexRoute
  '/comms/$conversationId': typeof AuthenticatedCommsConversationIdRoute
  '/events/$templateId': typeof AuthenticatedEventsTemplateIdRoute
  '/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/history/$workoutId': typeof AuthenticatedHistoryWorkoutIdRoute
  '/log/$workoutId': typeof AuthenticatedLogWorkoutIdRouteWithChildren
  '/log/new': typeof AuthenticatedLogNewRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/display/gym/$gymId': typeof DisplayGymGymIdRoute
  '/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/log/$workoutId/edit': typeof AuthenticatedLogWorkoutIdEditRoute
  '/profile/gyms/$gymId': typeof AuthenticatedProfileGymsGymIdRoute
  '/templates/$templateId/edit': typeof AuthenticatedTemplatesTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/comms': typeof AuthenticatedCommsRouteWithChildren
  '/connections': typeof AuthenticatedConnectionsRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gyms/join': typeof GymsJoinRoute
  '/s/$token': typeof STokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/display': typeof DisplayIndexRoute
  '/comms/$conversationId': typeof AuthenticatedCommsConversationIdRoute
  '/events/$templateId': typeof AuthenticatedEventsTemplateIdRoute
  '/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/history/$workoutId': typeof AuthenticatedHistoryWorkoutIdRoute
  '/log/$workoutId': typeof AuthenticatedLogWorkoutIdRouteWithChildren
  '/log/new': typeof AuthenticatedLogNewRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/display/gym/$gymId': typeof DisplayGymGymIdRoute
  '/exercises': typeof AuthenticatedExercisesIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/log/$workoutId/edit': typeof AuthenticatedLogWorkoutIdEditRoute
  '/profile/gyms/$gymId': typeof AuthenticatedProfileGymsGymIdRoute
  '/templates/$templateId/edit': typeof AuthenticatedTemplatesTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/connect': typeof ConnectRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRoute
  '/_authenticated/comms': typeof AuthenticatedCommsRouteWithChildren
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gyms/join': typeof GymsJoinRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/display/': typeof DisplayIndexRoute
  '/_authenticated/comms/$conversationId': typeof AuthenticatedCommsConversationIdRoute
  '/_authenticated/events/$templateId': typeof AuthenticatedEventsTemplateIdRoute
  '/_authenticated/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/history/$workoutId': typeof AuthenticatedHistoryWorkoutIdRoute
  '/_authenticated/log/$workoutId': typeof AuthenticatedLogWorkoutIdRouteWithChildren
  '/_authenticated/log/new': typeof AuthenticatedLogNewRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/display/gym/$gymId': typeof DisplayGymGymIdRoute
  '/_authenticated/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/log/$workoutId/edit': typeof AuthenticatedLogWorkoutIdEditRoute
  '/_authenticated/profile/gyms/$gymId': typeof AuthenticatedProfileGymsGymIdRoute
  '/_authenticated/templates/$templateId/edit': typeof AuthenticatedTemplatesTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/forgot-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/builder'
    | '/comms'
    | '/connections'
    | '/groups'
    | '/library'
    | '/profile'
    | '/vault'
    | '/auth/callback'
    | '/gyms/join'
    | '/s/$token'
    | '/display/'
    | '/comms/$conversationId'
    | '/events/$templateId'
    | '/exercises/$exerciseId'
    | '/groups/$groupId'
    | '/history/$workoutId'
    | '/log/$workoutId'
    | '/log/new'
    | '/templates/new'
    | '/display/gym/$gymId'
    | '/exercises/'
    | '/history/'
    | '/log/$workoutId/edit'
    | '/profile/gyms/$gymId'
    | '/templates/$templateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/forgot-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/builder'
    | '/comms'
    | '/connections'
    | '/groups'
    | '/library'
    | '/profile'
    | '/vault'
    | '/auth/callback'
    | '/gyms/join'
    | '/s/$token'
    | '/'
    | '/display'
    | '/comms/$conversationId'
    | '/events/$templateId'
    | '/exercises/$exerciseId'
    | '/groups/$groupId'
    | '/history/$workoutId'
    | '/log/$workoutId'
    | '/log/new'
    | '/templates/new'
    | '/display/gym/$gymId'
    | '/exercises'
    | '/history'
    | '/log/$workoutId/edit'
    | '/profile/gyms/$gymId'
    | '/templates/$templateId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/connect'
    | '/forgot-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/builder'
    | '/_authenticated/comms'
    | '/_authenticated/connections'
    | '/_authenticated/groups'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_authenticated/vault'
    | '/auth/callback'
    | '/gyms/join'
    | '/s/$token'
    | '/_authenticated/'
    | '/display/'
    | '/_authenticated/comms/$conversationId'
    | '/_authenticated/events/$templateId'
    | '/_authenticated/exercises/$exerciseId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/history/$workoutId'
    | '/_authenticated/log/$workoutId'
    | '/_authenticated/log/new'
    | '/_authenticated/templates/new'
    | '/display/gym/$gymId'
    | '/_authenticated/exercises/'
    | '/_authenticated/history/'
    | '/_authenticated/log/$workoutId/edit'
    | '/_authenticated/profile/gyms/$gymId'
    | '/_authenticated/templates/$templateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GymsJoinRoute: typeof GymsJoinRoute
  STokenRoute: typeof STokenRoute
  DisplayIndexRoute: typeof DisplayIndexRoute
  DisplayGymGymIdRoute: typeof DisplayGymGymIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/': {
      id: '/display/'
      path: '/display'
      fullPath: '/display/'
      preLoaderRoute: typeof DisplayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gyms/join': {
      id: '/gyms/join'
      path: '/gyms/join'
      fullPath: '/gyms/join'
      preLoaderRoute: typeof GymsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comms': {
      id: '/_authenticated/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof AuthenticatedCommsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises/': {
      id: '/_authenticated/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AuthenticatedExercisesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/display/gym/$gymId': {
      id: '/display/gym/$gymId'
      path: '/display/gym/$gymId'
      fullPath: '/display/gym/$gymId'
      preLoaderRoute: typeof DisplayGymGymIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log/new': {
      id: '/_authenticated/log/new'
      path: '/log/new'
      fullPath: '/log/new'
      preLoaderRoute: typeof AuthenticatedLogNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log/$workoutId': {
      id: '/_authenticated/log/$workoutId'
      path: '/log/$workoutId'
      fullPath: '/log/$workoutId'
      preLoaderRoute: typeof AuthenticatedLogWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/$workoutId': {
      id: '/_authenticated/history/$workoutId'
      path: '/history/$workoutId'
      fullPath: '/history/$workoutId'
      preLoaderRoute: typeof AuthenticatedHistoryWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/exercises/$exerciseId': {
      id: '/_authenticated/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof AuthenticatedExercisesExerciseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$templateId': {
      id: '/_authenticated/events/$templateId'
      path: '/events/$templateId'
      fullPath: '/events/$templateId'
      preLoaderRoute: typeof AuthenticatedEventsTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comms/$conversationId': {
      id: '/_authenticated/comms/$conversationId'
      path: '/$conversationId'
      fullPath: '/comms/$conversationId'
      preLoaderRoute: typeof AuthenticatedCommsConversationIdRouteImport
      parentRoute: typeof AuthenticatedCommsRoute
    }
    '/_authenticated/templates/$templateId/edit': {
      id: '/_authenticated/templates/$templateId/edit'
      path: '/templates/$templateId/edit'
      fullPath: '/templates/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/gyms/$gymId': {
      id: '/_authenticated/profile/gyms/$gymId'
      path: '/gyms/$gymId'
      fullPath: '/profile/gyms/$gymId'
      preLoaderRoute: typeof AuthenticatedProfileGymsGymIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/log/$workoutId/edit': {
      id: '/_authenticated/log/$workoutId/edit'
      path: '/edit'
      fullPath: '/log/$workoutId/edit'
      preLoaderRoute: typeof AuthenticatedLogWorkoutIdEditRouteImport
      parentRoute: typeof AuthenticatedLogWorkoutIdRoute
    }
  }
}

interface AuthenticatedCommsRouteChildren {
  AuthenticatedCommsConversationIdRoute: typeof AuthenticatedCommsConversationIdRoute
}

const AuthenticatedCommsRouteChildren: AuthenticatedCommsRouteChildren = {
  AuthenticatedCommsConversationIdRoute: AuthenticatedCommsConversationIdRoute,
}

const AuthenticatedCommsRouteWithChildren =
  AuthenticatedCommsRoute._addFileChildren(AuthenticatedCommsRouteChildren)

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileGymsGymIdRoute: typeof AuthenticatedProfileGymsGymIdRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileGymsGymIdRoute: AuthenticatedProfileGymsGymIdRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedLogWorkoutIdRouteChildren {
  AuthenticatedLogWorkoutIdEditRoute: typeof AuthenticatedLogWorkoutIdEditRoute
}

const AuthenticatedLogWorkoutIdRouteChildren: AuthenticatedLogWorkoutIdRouteChildren =
  {
    AuthenticatedLogWorkoutIdEditRoute: AuthenticatedLogWorkoutIdEditRoute,
  }

const AuthenticatedLogWorkoutIdRouteWithChildren =
  AuthenticatedLogWorkoutIdRoute._addFileChildren(
    AuthenticatedLogWorkoutIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRoute
  AuthenticatedCommsRoute: typeof AuthenticatedCommsRouteWithChildren
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventsTemplateIdRoute: typeof AuthenticatedEventsTemplateIdRoute
  AuthenticatedExercisesExerciseIdRoute: typeof AuthenticatedExercisesExerciseIdRoute
  AuthenticatedHistoryWorkoutIdRoute: typeof AuthenticatedHistoryWorkoutIdRoute
  AuthenticatedLogWorkoutIdRoute: typeof AuthenticatedLogWorkoutIdRouteWithChildren
  AuthenticatedLogNewRoute: typeof AuthenticatedLogNewRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedExercisesIndexRoute: typeof AuthenticatedExercisesIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
  AuthenticatedTemplatesTemplateIdEditRoute: typeof AuthenticatedTemplatesTemplateIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuilderRoute: AuthenticatedBuilderRoute,
  AuthenticatedCommsRoute: AuthenticatedCommsRouteWithChildren,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventsTemplateIdRoute: AuthenticatedEventsTemplateIdRoute,
  AuthenticatedExercisesExerciseIdRoute: AuthenticatedExercisesExerciseIdRoute,
  AuthenticatedHistoryWorkoutIdRoute: AuthenticatedHistoryWorkoutIdRoute,
  AuthenticatedLogWorkoutIdRoute: AuthenticatedLogWorkoutIdRouteWithChildren,
  AuthenticatedLogNewRoute: AuthenticatedLogNewRoute,
  AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
  AuthenticatedExercisesIndexRoute: AuthenticatedExercisesIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  AuthenticatedTemplatesTemplateIdEditRoute:
    AuthenticatedTemplatesTemplateIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConnectRoute: ConnectRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GymsJoinRoute: GymsJoinRoute,
  STokenRoute: STokenRoute,
  DisplayIndexRoute: DisplayIndexRoute,
  DisplayGymGymIdRoute: DisplayGymGymIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
