/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedExercisesIndexRouteImport } from './routes/_authenticated/exercises/index'
import { Route as AuthenticatedLogWorkoutIdRouteImport } from './routes/_authenticated/log.$workoutId'
import { Route as AuthenticatedHistoryWorkoutIdRouteImport } from './routes/_authenticated/history/$workoutId'
import { Route as AuthenticatedExercisesExerciseIdRouteImport } from './routes/_authenticated/exercises/$exerciseId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExercisesIndexRoute =
  AuthenticatedExercisesIndexRouteImport.update({
    id: '/exercises/',
    path: '/exercises/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogWorkoutIdRoute =
  AuthenticatedLogWorkoutIdRouteImport.update({
    id: '/log/$workoutId',
    path: '/log/$workoutId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryWorkoutIdRoute =
  AuthenticatedHistoryWorkoutIdRouteImport.update({
    id: '/history/$workoutId',
    path: '/history/$workoutId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExercisesExerciseIdRoute =
  AuthenticatedExercisesExerciseIdRouteImport.update({
    id: '/exercises/$exerciseId',
    path: '/exercises/$exerciseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
  '/history/$workoutId': typeof AuthenticatedHistoryWorkoutIdRoute
  '/log/$workoutId': typeof AuthenticatedLogWorkoutIdRoute
  '/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
  '/history/$workoutId': typeof AuthenticatedHistoryWorkoutIdRoute
  '/log/$workoutId': typeof AuthenticatedLogWorkoutIdRoute
  '/exercises': typeof AuthenticatedExercisesIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
  '/_authenticated/history/$workoutId': typeof AuthenticatedHistoryWorkoutIdRoute
  '/_authenticated/log/$workoutId': typeof AuthenticatedLogWorkoutIdRoute
  '/_authenticated/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/builder'
    | '/library'
    | '/profile'
    | '/vault'
    | '/auth/callback'
    | '/exercises/$exerciseId'
    | '/history/$workoutId'
    | '/log/$workoutId'
    | '/exercises/'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/builder'
    | '/library'
    | '/profile'
    | '/vault'
    | '/auth/callback'
    | '/'
    | '/exercises/$exerciseId'
    | '/history/$workoutId'
    | '/log/$workoutId'
    | '/exercises'
    | '/history'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/builder'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_authenticated/vault'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/exercises/$exerciseId'
    | '/_authenticated/history/$workoutId'
    | '/_authenticated/log/$workoutId'
    | '/_authenticated/exercises/'
    | '/_authenticated/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises/': {
      id: '/_authenticated/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AuthenticatedExercisesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log/$workoutId': {
      id: '/_authenticated/log/$workoutId'
      path: '/log/$workoutId'
      fullPath: '/log/$workoutId'
      preLoaderRoute: typeof AuthenticatedLogWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/$workoutId': {
      id: '/_authenticated/history/$workoutId'
      path: '/history/$workoutId'
      fullPath: '/history/$workoutId'
      preLoaderRoute: typeof AuthenticatedHistoryWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises/$exerciseId': {
      id: '/_authenticated/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof AuthenticatedExercisesExerciseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExercisesExerciseIdRoute: typeof AuthenticatedExercisesExerciseIdRoute
  AuthenticatedHistoryWorkoutIdRoute: typeof AuthenticatedHistoryWorkoutIdRoute
  AuthenticatedLogWorkoutIdRoute: typeof AuthenticatedLogWorkoutIdRoute
  AuthenticatedExercisesIndexRoute: typeof AuthenticatedExercisesIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuilderRoute: AuthenticatedBuilderRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExercisesExerciseIdRoute: AuthenticatedExercisesExerciseIdRoute,
  AuthenticatedHistoryWorkoutIdRoute: AuthenticatedHistoryWorkoutIdRoute,
  AuthenticatedLogWorkoutIdRoute: AuthenticatedLogWorkoutIdRoute,
  AuthenticatedExercisesIndexRoute: AuthenticatedExercisesIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
